.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH 0k-core 1  "0k-core 0.3.0" 
.SH NAME
0k\-core \- Manages SquashFS archives
.SH SYNOPSIS
\fB0k\-core\fR [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] 
.SH DESCRIPTION
Manages SquashFS archives
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH EXTRA
Detailed Command Information:

  create <INPUT> [OUTPUT] [OPTIONS]
    Convert a directory or an archive into a SquashFS image.
    Arguments:
      INPUT                 Source directory or archive file.
      OUTPUT                (Optional) Path to the resulting image.
    Options:
      \-e, \-\-encrypt         Create an encrypted LUKS container (Requires root/sudo).
      \-c, \-\-compression N   Zstd compression level (default: 19) 0 = no compression.
      \-\-no\-progress         Disable progress bar completely.
      \-\-vanilla\-progress    Use native mksquashfs progress (explicit, also default).
      \-\-alfa\-progress       Use experimental custom progress bar (not fixed in encryption mode, yet; for testing).

    Supported Input Formats (repacked on\-the\-fly via pipe):
      \- Directory: Standard behavior
      \- Tarball:   .tar (requires \*(Aqcat\*(Aq)
      \- Combos:    .tar.gz, .tgz (requires \*(Aqgzip\*(Aq)
                   .tar.bz2, .tbz2 (requires \*(Aqbzip2\*(Aq)
                   .tar.xz, .txz (requires \*(Aqxz\*(Aq)
                   .tar.zst, .tzst (requires \*(Aqzstd\*(Aq)
                   .tar.zip (requires \*(Aqunzip\*(Aq)
                   .tar.7z (requires \*(Aq7z\*(Aq)
                   .tar.rar (requires \*(Aqunrar\*(Aq)
      Note: Archive repacking requires \*(Aqtar2sqfs\*(Aq (from squashfs\-tools\-ng) installed.

  mount <IMAGE> [MOUNT_POINT]
    Mount a SquashFS image as a directory.
    Arguments:
      IMAGE                 Path to the SquashFS image file.
      MOUNT_POINT           (Optional) Manual mount point.
                            Generated if omitted (prefix_timestamp_random).

  umount <TARGET>
    Unmounts a directory or all instances of an image.
    Arguments:
      TARGET                Mount point directory OR path to the image file.
.SH VERSION
v0.3.0
